name: AI Orchestrator Scheduler

on:
  schedule:
    # Generation: every minute
    - cron: '*/1 * * * *'
    # Cleanup: daily at 22:00 UTC (~03:30 IST)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  generate:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '*/1 * * * *'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ai-orchestrator-generate
      cancel-in-progress: true
    env:
  FUNCTION_URL: https://gcheopiqayyptfxowulv.supabase.co/functions/v1/ai-orchestrator
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Validate secrets
        run: |
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET not set as a repo secret" >&2
            exit 1
          fi
      - name: POST to ai-orchestrator (run)
        run: |
          set -e
          http_code=$(curl -sS -o resp.json -w "%{http_code}" -X POST "$FUNCTION_URL" \
            -H "X-Cron-Secret: $CRON_SECRET" \
            -H "Authorization: Bearer $ANON_KEY" -H "apikey: $ANON_KEY" \
            -H "Content-Type: application/json" -d '{}')
          echo "HTTP $http_code"
          cat resp.json || true
          test "$http_code" -ge 200 && test "$http_code" -lt 300

  cleanup:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 22 * * *'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ai-orchestrator-cleanup
      cancel-in-progress: true
    env:
  FUNCTION_URL: https://gcheopiqayyptfxowulv.supabase.co/functions/v1/ai-orchestrator?task=cleanup
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Validate secrets
        run: |
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET not set as a repo secret" >&2
            exit 1
          fi
      - name: POST to ai-orchestrator (cleanup)
        run: |
          set -e
          http_code=$(curl -sS -o resp.json -w "%{http_code}" -X POST "$FUNCTION_URL" \
            -H "X-Cron-Secret: $CRON_SECRET" \
            -H "Authorization: Bearer $ANON_KEY" -H "apikey: $ANON_KEY" \
            -H "Content-Type: application/json" -d '{}')
          echo "HTTP $http_code"
          cat resp.json || true
          test "$http_code" -ge 200 && test "$http_code" -lt 300
