name: AI Orchestrator - Generate

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ai-orchestrator-generate
      cancel-in-progress: true
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      FUNCTION_URL: ${{ secrets.SUPABASE_URL }}/functions/v1/ai-orchestrator
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Validate secrets
        run: |
          if [ -z "$CRON_SECRET" ] || [ -z "$SUPABASE_URL" ] || [ -z "$ANON_KEY" ]; then
            echo "Missing required secrets (CRON_SECRET, SUPABASE_URL, SUPABASE_ANON_KEY)" >&2
            exit 1
          fi
      - name: POST to ai-orchestrator (run)
        run: |
          set -e
          http_code=$(curl -sS -o resp.json -w "%{http_code}" -X POST "$FUNCTION_URL" \
            -H "X-Cron-Secret: $CRON_SECRET" \
            -H "Authorization: Bearer $ANON_KEY" -H "apikey: $ANON_KEY" \
            -H "Content-Type: application/json" -d '{}')
          echo "HTTP $http_code"
          cat resp.json || true
          test "$http_code" -ge 200 && test "$http_code" -lt 300
