name: AI Orchestrator - Cleanup

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: none
      actions: none
      checks: none
      packages: none
      deployments: none
      security-events: none
    concurrency:
      group: ai-orchestrator-cleanup
      cancel-in-progress: true
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      FUNCTION_URL: ${{ secrets.SUPABASE_URL }}/functions/v1/ai-orchestrator?task=cleanup
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Validate secrets
        run: |
          if [ -z "$CRON_SECRET" ] || [ -z "$SUPABASE_URL" ] || [ -z "$ANON_KEY" ]; then
            echo "Missing required secrets (CRON_SECRET, SUPABASE_URL, SUPABASE_ANON_KEY)" >&2
            exit 1
          fi
      - name: POST to ai-orchestrator (cleanup)
        run: |
          set -e
          MAX_TRIES=5
          attempt=1
          success=0
          while [ $attempt -le $MAX_TRIES ]; do
            echo "Attempt $attempt/$MAX_TRIES..."
            set +e
            http_code=$(curl -sS -o resp.json -w "%{http_code}" -X POST "$FUNCTION_URL" \
              --connect-timeout 8 --max-time 25 \
              -H "X-Cron-Secret: $CRON_SECRET" \
              -H "Authorization: Bearer $ANON_KEY" -H "apikey: $ANON_KEY" \
              -H "Content-Type: application/json" -d '{}')
            curl_exit=$?
            set -e
            echo "curl exit: $curl_exit | HTTP: $http_code"
            if [ $curl_exit -eq 0 ] && [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
              success=1
              break
            fi
            if [ $attempt -lt $MAX_TRIES ]; then
              delay=$(( (2 ** attempt) + (RANDOM % 3) ))
              echo "Transient error. Retrying in ${delay}s..."
              sleep $delay
            fi
            attempt=$((attempt + 1))
          done
          echo "Final HTTP: $http_code"; cat resp.json || true
          test $success -eq 1

  auto-rerun:
    name: Auto rerun on failure
    needs: [cleanup]
    if: failure() && github.run_attempt < 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Re-run this workflow (attempt ${{ github.run_attempt + 1 }})
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.info(`Re-running workflow run ${context.runId} (attempt ${context.runAttempt})`)
            await github.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })
