name: Deploy Supabase Edge Functions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        run: npm i -g supabase@latest

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN secret" >&2; exit 1; fi
          echo "Logged in via token (provided by secret)"

      - name: Link project
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          if [ -z "$SUPABASE_PROJECT_REF" ]; then
            echo "Missing SUPABASE_PROJECT_REF secret" >&2; exit 1; fi
          supabase link --project-ref "$SUPABASE_PROJECT_REF" --workdir ./

      - name: Deploy functions
        run: |
          supabase functions deploy ai-orchestrator --project-ref "$SUPABASE_PROJECT_REF"
          supabase functions deploy admin-upsert-questions --project-ref "$SUPABASE_PROJECT_REF"
